name: CADE
favicon: null
layout_spectrum: 0.9196
typography_spectrum: 0.41667
title: Finding a Job Just got Easier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c07'
    - '#ffffff'
    - '#9b9389'
    - '#5a5143'
    - '#c6b7a1'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
