name: CADE
favicon: null
layout_spectrum: 0.875
typography_spectrum: 0.4739
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: CADE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c07'
    - '#ffffff'
    - '#9b9389'
    - '#5a5143'
    - '#c6b7a1'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
