name: CADE
favicon: null
layout_spectrum: 0.87639
typography_spectrum: 0.04226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#445366'
    - '#141319'
    - '#b57130'
    - '#ff70bf'
  brandStrength: 0.3125
  lightness: 0.9479119007010013
  saturation: 0.5
  rhythmicContrast: 0.3846923573873937
purpose: []
