name: CADE
favicon: null
layout_spectrum: 0.89969
typography_spectrum: 0.36265
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: CADE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c07'
    - '#ffffff'
    - '#9b9389'
    - '#5a5143'
    - '#c6b7a1'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
