name: CADE
favicon: null
layout_spectrum: 0.9196
typography_spectrum: 0.41667
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c07'
    - '#ffffff'
    - '#9b9389'
    - '#5a5143'
    - '#c6b7a1'
  brandStrength: 0.0625
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.3846923573873937
purpose: []
