name: CADE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32112
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Finding a Job Just got Easier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0c07'
    - '#ffffff'
    - '#9b9389'
    - '#5a5143'
    - '#c6b7a1'
  brandStrength: 0.3125
  lightness: 0.677909
  saturation: 0.9165261
  rhythmicContrast: 0.1053963
purpose: []
